### PR TITLE
Add unit tests for u2flib_host.utils

### PR DESCRIPTION
**Pull request by moreati**

### CODE REVIEW

**Comment by dainnilsson** [comment]
Thanks! Can you state that you contribute this code under the license of the project? Please note that the project has recently changed license from GPL to BSD 2-clause, you will need to state that you contribute under the BSD license for us to merge this.

**Comment by moreati** [comment]
I state that this code is my own work, and that I am contributing it under the BSD 2-clause licence

**Comment by dainnilsson** [comment]
Thank you!

**Comment by moreati** [comment]
Oh, you switched from nose to unittest. I'll submit a new PR.

**Comment by dainnilsson** [comment]
Ah, whoops. Sorry about that!

**Pull request merged**
