### PR TITLE
Fix uncaught exceptions preventing the YubiKey Nano to be listed

### LINKED ISSUE #25: Yubikey Nano 4 not returned by u2f.list_devices()
The following exception (which is silently ignored) prevent the Yubikey Nano 4 to be listed by u2f.list_devices() on MacOSX (not sure about the other OS):

Python  2.7:
```
Python 2.7.10 (default, Feb  7 2017, 00:08:15) 
[GCC 4.2.1 Compatible Apple LLVM 8.0.0 (clang-800.0.34)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> from u2flib_host import hid_transport
>>> hid_transport.list_devices()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/prousset/Library/Python/2.7/lib/python/site-packages/u2flib_host/hid_transport.py", line 81, in list_devices
    device.open()
  File "/Users/prousset/Library/Python/2.7/lib/python/site-packages/u2flib_host/hid_transport.py", line 116, in open
    self.handle.open_path(self.path)
  File "hid.pyx", line 72, in hid.device.open_path (hid.c:1909)
IOError: open failed
```

Python  3:
```
Python 3.6.1 (default, Apr  4 2017, 09:40:21) 
[GCC 4.2.1 Compatible Apple LLVM 8.1.0 (clang-802.0.38)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> from u2flib_host import hid_transport
>>> hid_transport.list_devices()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.6/site-packages/u2flib_host/hid_transport.py", line 81, in list_devices
    device.open()
  File "/usr/local/lib/python3.6/site-packages/u2flib_host/hid_transport.py", line 116, in open
    self.handle.open_path(self.path)
  File "hid.pyx", line 72, in hid.device.open_path (hid.c:1909)
OSError: open failed
```

### PR DESCRIPTION
**Pull request by dahu33**
This pull request should fix #25.

On another note, I'm not sure why exceptions are silently ignored here, maybe this could be removed? https://github.com/Yubico/python-u2flib-host/blob/master/u2flib_host/u2f.py#L49

### CODE REVIEW

**Comment by dainnilsson** [comment]
The reason for catching and ignoring the exception is to continue with the next device if one fails with a DeviceError, instead of raising the exception and failing without looking for additional devices.

The change in this PR causes it to catch ANY exception and continue with the next device. What exception are you getting that is causing problems? I'd prefer explicitly catching the exceptions that may occur during operation (and understanding why they occur) to just catching anything.

**Comment by dainnilsson** [comment]
Nevermind, I just read the related issue comment, which includes the traceback. I'm not sure what is causing the open to fail, but I'd prefer a change where the IOError is caught in addition to the DeviceError. Care to make the change?

**Comment by dahu33** [comment]
@dainnilsson made the requested change. Looking forward to using version 3.0.2 :)

FYI: the Nano is also "simulating a keyboard" so it's caught twice in the loop (https://github.com/dahu33/python-u2flib-host/blob/869dc7c8e2bc6c47d8bec19caf2d8b94acbf01c3/u2flib_host/hid_transport.py#L78). The output of hid.enumerate(0, 0) on my laptop with Nano:
```
{'usage_page': 1, 'product_id': 1031, 'interface_number': -1, 'manufacturer_string': u'Yubico', 'vendor_id': 4176, 'release_number': 1076, 'serial_number': u'', 'usage': 6, 'path': 'IOService:/AppleACPIPlatformExpert/PCI0@0/AppleACPIPCI/XHC1@14/XHC1@14000000/HS02@14200000/Yubikey 4 OTP+U2F+CCID@14200000/IOUSBHostInterface@0/IOUSBHostHIDDevice@14200000,0', 'product_string': u'Yubikey 4 OTP+U2F+CCID'}
{'usage_page': 61904, 'product_id': 1031, 'interface_number': -1, 'manufacturer_string': u'Yubico', 'vendor_id': 4176, 'release_number': 1076, 'serial_number': u'', 'usage': 1, 'path': 'IOService:/AppleACPIPlatformExpert/PCI0@0/AppleACPIPCI/XHC1@14/XHC1@14000000/HS02@14200000/Yubikey 4 OTP+U2F+CCID@14200000/IOUSBHostInterface@1/IOUSBHostHIDDevice@14200000,1', 'product_string': u'Yubikey 4 OTP+U2F+CCID'}
```

**Comment by dainnilsson** [comment]
Thanks for the extra info, that explains it. Changes look good, will merge now.

**Comment by dainnilsson** [comment]
BTW, any other small changes you're aware of that you'd like to submit before I do a 3.0.2 release?

**Comment by dahu33** [comment]
Our python 3 application has been running without new issue for the last two days using both the YubiKey Nano and FIDO U2F. I think we are good for now :) Thanks for the help!

**Pull request merged**
